//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_VENDINGMACHINE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MachineVendingEntities : DbContext
    {
        public MachineVendingEntities()
            : base("name=MachineVendingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Change> Change { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<LoginTime> LoginTime { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolesPermissionXml> RolesPermissionXml { get; set; }
        public virtual DbSet<Security> Security { get; set; }
        public virtual DbSet<Slots> Slots { get; set; }
        public virtual DbSet<Solded> Solded { get; set; }
        public virtual DbSet<Vending_Machine> Vending_Machine { get; set; }
        public virtual DbSet<PriceUpdated> PriceUpdated { get; set; }
    }
}
