//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_VENDINGMACHINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slots
    {
        public int Id_Slot { get; set; }
        public int Id_Machine { get; set; }
        public int Id_Product { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Slot_Number { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Vending_Machine Vending_Machine { get; set; }
    }
}
